### ISSUE TITLE
error during shiny app start up

### ISSUE THREAD

**Issue by dylanmikesell** [mathedjoe/animaltracker#35]
I get the following error when running the animaltracker app. This occurs during startup and the app hangs.

> run_shiny_animaltracker()
Loading required namespace: shinyWidgets
Loading required namespace: shinycssloaders
Loading required namespace: shinythemes
Loading required namespace: sp
Loading required namespace: raster
Loading required namespace: shinyjs
Loading required namespace: V8
Loading required namespace: shinyBS
Loading required package: shiny

Listening on http://127.0.0.1:6432
Warning in utils::unzip(filename, exdir = dirname(exdir)) :
  error 1 in extracting from zip file
Warning: Error in [[: subscript out of bounds
  50: raster::raster
  49: read_zip_to_rasters
  48: server
Error in f[[1]] : subscript out of bounds

I have tried this on two computers now.  Running R version 3.6.1 with the latest version of animaltracker installed from GitHub following the instructions on the animaltracker site.

**Comment by ttsukianto** [comment]
Fixed as of last commit to master, ran on R 3.6.1 with Windows 10 and Mac OS X.
