### ISSUE TITLE
Columbus P-1 read capability

### ISSUE THREAD

**Issue by dylanmikesell** [mathedjoe/animaltracker#39]
Because we are now also using the [Columbus P-1 GPS sensors](http://www.semsons.com/cop1prgpsdal.html), we need the ability to read RAW data from those sensors. The sensor outputs three formats: CSV, GPX (XML format), and  TXT ([NMEA](https://www.gpsinformation.org/dale/nmea.htm) format). Of the three formats, NMEA is the only output that provides information about the satellites and waypoint solution information (e.g. HDOP). I have attached an example NMEA file. Each line is a NMEA "sentence" and begins with the corresponding NMEA code (see bold below). Each data point has two NMEA sentences (RMC and GGA). 

$GP**RMC**,192352.799,A,4336.0500,N,11611.8394,W,0.00,0.00,301019,,,A*78
$GP**GGA**,192352.899,4336.0500,N,11611.8393,W,1,04,2.63,755.6,M,-18.6,M,,0000*58
$GP**RMC**,192352.899,A,4336.0500,N,11611.8393,W,0.00,0.00,301019,,,A*70
$GP**GGA**,192353.000,4336.0500,N,11611.8391,W,1,04,2.64,755.8,M,-18.6,M,,0000*5A

We need to add functionality to AnimalTracker to read NMEA text files. We need a flag that first looks at the file extension. Then if it is a TXT file, it needs to read the first row of the first line and determine if the file is NMEA (e.g. is row 1, col 1 equal to $GPRMC). Then we need to parse the data associated with each waypoint. The attached PDF file explains the components of each NMEA sentence, and the colors in the example sentences highlight the important parameters that I think we will want to extract from the files.

[NMEA_sentences.pdf](https://github.com/mathedjoe/animaltracker/files/3794313/NMEA_sentences.pdf)

[30192350.TXT](https://github.com/mathedjoe/animaltracker/files/3794278/30192350.TXT)

**Comment by mathedjoe** [comment]
@dylanmikesell - can you take a look at this processed version of your sample data file (rename to .csv to open in excel)? I think I got the important information, but we can easily adjust.
[sample_processed_data.txt](https://github.com/mathedjoe/animaltracker/files/3810651/sample_processed_data.txt)

**Comment by dylanmikesell** [comment]
I think you're good to go. It looks like you got all of the important parts.

**Comment by ttsukianto** [comment]
When a user uploads data through the app, would I assume iGotU and Columbus P-1 datasets are in separate folders or could they potentially upload both types of data in the same folder?

**Comment by dylanmikesell** [comment]
I think they could be the same folder. We just need some distinguishing
file name or header. You can store in separate folders if you prefer. But
the two folders should then be under a data folder or something and have
practical names related to the data.

**Comment by mathedjoe** [comment]
Typical use case might be all one format, but I think we should "peek" into
every file, determine the format, and read/process accordingly. That may
require a little refactoring of the code, but I think it's the right way to
go and won't affect performance much.

Joe
