### ISSUE TITLE
R Session Aborts

### ISSUE THREAD

**Issue by arispes** [mathedjoe/animaltracker#46]
Thea,

Each time I run a .zip file with sample datasets in Animal Tracker my R Session Aborts.  I'm attaching the dataset and a screenshot.  My RStudio and R software are up to date.

[W_cow_337_16.csv.zip](https://github.com/mathedjoe/animaltracker/files/3943018/W_cow_337_16.csv.zip)

<img width="1679" alt="Screen Shot 2019-12-09 at 9 26 49 PM" src="https://user-images.githubusercontent.com/45365827/70495392-07d05b00-1acb-11ea-9929-42c8067a8c64.png">

Sergio

**Comment by mathedjoe** [comment]
@arispes and I just sat down and verified this is due to memory overload. At high resolution, the app will need to divide up the elevation lookup into batches.

**Comment by mathedjoe** [comment]
one additional thought - perhaps the memory error happens when the app tries to draw a huge dataset? (Probably not.)
