### ISSUE TITLE
Remove "0" satellite data

### ISSUE THREAD

**Issue by arispes** [mathedjoe/animaltracker#48]
After cleaning datasets with AnimalTracker, I noticed there are some lines with "0" satellites.  Is it possible to remove those data?

**Comment by arispes** [comment]
[Archive.zip](https://github.com/mathedjoe/animaltracker/files/3943099/Archive.zip)
Data with datapoints from "0" satellites.

**Comment by mathedjoe** [comment]
seems like a "duh" filtering condition... we'll look it over to confirm, and then include it in the app
