### ISSUE TITLE
use clipped data for elevation lookup

### ISSUE THREAD

**Issue by mathedjoe** [mathedjoe/animaltracker#49]
The app appears to use uploaded data only when running the elevation lookup functions. Ideally, if users clip the data using the map tools, then the elevation lookup function would be applied to just the selected data (this could help with obtaining high resolution elevation estimates for selected data within a narrow geographic area)

**Comment by dylanmikesell** [comment]
Not sure if this is related to this issue or not, but I think it might be given we are talking about low-res elevation data. Angela has been plotting data using the cleaned data outputs from Animal Tracker. Attached is a zip file that contains 4 plots.

1. Lat/Lon of cow 102
2. Altitude vs. time of cow 102
3. Slope vs. time of cow 102
4. Elevation vs. time of cow 102

It is our understanding that the slope and elevation are computed parameters from the Animal Tracker code. Have a look at the plots. There is something strange happening with the computed parameters and I wonder if it is from the underlying elevation lookup data. I could imagine that low res data would lead to what we observe in these plots. The slope and elevation plots should look more continuous like the altitude plot.

[plots.zip](https://github.com/mathedjoe/animaltracker/files/4112978/plots.zip)
